version: '{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
skip_commits:
  files:
  - doc/*
  - readme.md
  - license.md

nuget:
  disable_publish_on_pr: true

install:
- cmd: git submodule update --init --recursive

before_build:
- cmd: msbuild Confuser2.sln @appveyor_restore.rsp /m

build:
  project: Confuser2.sln
  verbosity: minimal 
  parallel: true

artifacts:
- path: Release/bin
  name: ConfuserEx
  type: zip
- path: Confuser.MSBuild.Tasks/bin/Release/*.nupkg
  name: ConfuserEx.MSBuild

for:
-
  branches:
    except:
      - master

  build:
    publish_nuget: false

on_failure:
- appveyor PushArtifact msbuild.binlog

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/7ff0ea601d40c1b3fcaa
  on_build_success: true
  on_build_failure: true

deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: "ConfuserEx $(APPVEYOR_REPO_TAG_NAME) Release"
  auth_token:
    secure: NTT+Z1zBxbj+w8jroqhYJnI2urxSt0gq3MUmDavUPVKZL+YX4krR4xJQ5OmHYhcG
  on:
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  api_key:
    secure: g1HSOpBz5QurbLPHE06OFyRLxK7HF8Q88mk6dh3ifG7dULhsampXh07ZR+VBhj8iW
  on:
    APPVEYOR_REPO_TAG: true